### ISSUE TITLE
Программа падает, при нажатии на кнопку

### ISSUE THREAD

**Issue by Inwusg** [mikho1l/P1XEL#1]
1. Заходим в программу, вводим логин, пароль.
![Screenshot_16](https://user-images.githubusercontent.com/90562739/146734265-454ed881-7795-4f3e-b642-d037a556015c.png)
2. В открывшемся окне, после входа, нажимаем кнопку (на скриншоте выделена красным).
![Screenshot_17](https://user-images.githubusercontent.com/90562739/146734473-c70fb6ff-03bd-4c85-882d-ed71906f57b3.png)
3. Приложение подвисает на время и падает.

**Comment by mikho1l** [comment]
Мы передали Вашу информацию разработчикам. Спасибо за Ваш вклад в развитие нашего продукта. Получите приз 

![image](https://user-images.githubusercontent.com/93985330/146779240-327e44b5-b962-458a-b503-c869e0d33bc3.png)
