### ISSUE TITLE
Невозможность добавить клиента

### ISSUE THREAD

**Issue by Inwusg** [mikho1l/P1XEL#2]
1. Заходим в программу, вводим логин, пароль.
![Screenshot_16](https://user-images.githubusercontent.com/90562739/146734899-e92d32ec-9865-47e4-9fb6-3b5c63fe5857.png)
2. В открывшемся окне нажимаем кнопку "База клиентов".
![Screenshot_17](https://user-images.githubusercontent.com/90562739/146735208-c57cfece-d4b4-4926-bdee-751a1f94323d.png)
3. В открывшемся окне нажимаем кнопку "+Клиент".
![Screenshot_18](https://user-images.githubusercontent.com/90562739/146735329-c1e25ef4-56ce-45a8-a6f3-ca0f6f996560.png)
4. В открывшемся окне заполняем данные и нажимаем кнопку "Добавить".
![Screenshot_19](https://user-images.githubusercontent.com/90562739/146735555-a0ee6f0e-36bd-4973-aee3-b0319e20f0d8.png)
5. Видим, что в таблицу добавилась пустая строчка.
![Screenshot_20](https://user-images.githubusercontent.com/90562739/146735662-ae833b88-80da-4011-8bea-b344ec5ed21d.png)

**Comment by mikho1l** [comment]
Эта функция только для подписчиков Pixel Premium. _купить подписку_
