### ISSUE TITLE
Невозможность добавить продажу

### ISSUE THREAD

**Issue by Inwusg** [mikho1l/P1XEL#3]
1. Заходим в программу, вводим логин, пароль.
![Screenshot_16](https://user-images.githubusercontent.com/90562739/146736365-8baa54c2-5217-4ca2-aebf-b9e9b25795d3.png)
2. В открывшемся окне нажимаем кнопку "+Продажа".
![Screenshot_17](https://user-images.githubusercontent.com/90562739/146736493-bc41df18-0c10-4abe-862f-b052e68ed736.png)
3. В открывшемся окне выбираем наименование товара (1), способ оплаты (2) и нажимаем кнопку "Добавить" (3).
![Screenshot_24](https://user-images.githubusercontent.com/90562739/146736697-6f9e6f8d-40d0-4014-94d1-d137f4c7afa8.png)
4. Видим, что ничего не поменялось.
![Screenshot_25](https://user-images.githubusercontent.com/90562739/146736741-27d4cd4e-8158-46a2-890a-58d06b8b2559.png)

**Comment by mikho1l** [comment]
Всё невозможное возможно, я знаю точно,
Сойти с ума, влюбиться так неосторожно

![image](https://user-images.githubusercontent.com/93985330/146778878-75f31fe1-cb47-4d10-9050-66b104267939.png)
