### ISSUE TITLE
Вход в приложение по любой комбинации символов в поле пароль

### ISSUE THREAD

**Issue by Beskovaaa** [mikho1l/P1XEL#4]
1. Зходим в программу, выбираем логин и вводим пароль (или не вводим)
![image](https://user-images.githubusercontent.com/93737292/146829603-a8205641-de66-4e2b-bb3e-04563d9ba40a.png)
![image](https://user-images.githubusercontent.com/93737292/146829618-023a6bde-ac53-4665-a2ab-2dbb0b11d880.png)
2. Программа авторизируется при любом заполнении поля пароль
Ожидаемое поведение: вход по индивидуальному (не пустому) паролю.

**Comment by ValeriaBogdanyuk** [comment]
у нас пока что беспарольный вход
