### ISSUE TITLE
Смещение элементов на экране

### ISSUE THREAD

**Issue by Beskovaaa** [mikho1l/P1XEL#5]
1. Авторизируемся в приложении
2. Решаем открыть приложение во весь экран
![image](https://user-images.githubusercontent.com/93737292/146831380-620cbe6c-e4b5-40c0-906f-9f6f1f823368.png)
Кнопки заезжают на окна
3. Сворачиваем окно обратно 
![image](https://user-images.githubusercontent.com/93737292/146831525-789acdcc-7edb-4b3a-bebd-52de74129007.png)
Кнопки на половину скрываются
Ожидаемое поведение: кнопки остаются на местах и не обрезаются

**Comment by ValeriaBogdanyuk** [comment]
кто сказал, что можно растягивать, больше нельзя
