### ISSUE TITLE
Невозможно добавить новую бронь

### ISSUE THREAD

**Issue by Beskovaaa** [mikho1l/P1XEL#7]
1. Авторизируемся в приложении
2. Вводим данные для новой брони
![image](https://user-images.githubusercontent.com/93737292/146832917-ccb6e17f-5a17-4661-9d20-32db45e2bfad.png)
3. Новая бронь не добавилась
![image](https://user-images.githubusercontent.com/93737292/146832997-664f58e4-acf7-41c9-a7c4-a4550c7cf746.png)
Ожидаемое поведение: добавление брони

**Comment by ValeriaBogdanyuk** [comment]
Женам без мужей нельзя, вот и не добавляет
